ALTER TABLE Jocs DROP CONSTRAINT FK_Jocs_ID
ALTER TABLE Packs DROP CONSTRAINT FK_Packs_ID
ALTER TABLE Pack_LISTAJUEGOS DROP CONSTRAINT FK_Pack_LISTAJUEGOS_Pack_ID
DROP TABLE Productes CASCADE
DROP TABLE Jocs CASCADE
DROP TABLE Packs CASCADE
DROP TABLE Pack_LISTAJUEGOS CASCADE
DELETE FROM SEQUENCE WHERE SEQ_NAME = 'SEQ_GEN'
